---

name: NX1 Deploy to self-contained-ohio-dev1
run-name: Deploy to self-contained-ohio-dev1 (us-east-2/481313360369) by @${{ github.actor }}

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: NX1 Deploy
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Optional step: Detect app and construct Dockerfile using Nixpacks
      - name: NX1 Build with Nixpacks
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'build-nixpacks'

      - name: NX1 Prepare Deployment
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'prepare'
          api_url: 'https://dev-app.citadel.run/api'
          app_id: 9b612b36-d1bc-49b8-b006-0a62b55c288f
          api_token: ${{ secrets.NX1_API_TOKEN }}
          env_id: 4c902cae-c43f-4be0-83b6-0df7173f8184

      - name: NX1 Assume Role
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'assume-role'

      - name: NX1 Deploy Service - web
        uses: nx1-io/app-copilot-action@feature/deploy-fail-logs
        with:
          operation: 'deploy'
          service: 'web'

      # Optional step: Migrate database
      - name: NX1 Migrate Service - web
        uses: nx1-io/app-copilot-action@main
        with:
          operation: 'run'
          service: 'web'
          command: 'yarn migrate:deploy && yarn seed' # replace with your migration command

# rev:1
